{% set name = "sciris" %}
{% set version = "3.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sciris-{{ version }}.tar.gz
  sha256: 86323196481ca5e1e805842028e3d02be47346a31ca54713260a180efcdb82d6

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - pandas
    - openpyxl
    - xlsxwriter
    - psutil
    - dill
    - zstandard
    - multiprocess
    - jsonpickle
    - pyyaml
    - packaging
    - setuptools
    - gitpython
    - jellyfish
    - tqdm
    - python-dateutil
    - line_profiler
    - memory_profiler
    - colorama

test:
  imports:
    - sciris
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://sciris.org
  summary: Fast, flexible tools to simplify scientific Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Sciris is a library of tools that can help make writing scientific 
    Python code easier and more pleasant. Built on top of NumPy and 
    Matplotlib, Sciris provides functions covering a wide range of common 
    array, file I/O, and plotting operations.
  doc_url: https://docs.sciris.org/
  dev_url: https://github.com/sciris/sciris

extra:
  recipe-maintainers:
    - cliffckerr
