{% set name = "sciris" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sciris-{{ version }}.tar.gz
  sha256: f6e9b112a84650e470b1c085d4f533cacf8b0839083b875d1db0af7dcd87c437

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base
    - numpy
    - pandas
    - openpyxl
    - xlsxwriter
    - psutil
    - dill
    - zstandard
    - multiprocess
    - jsonpickle
    - pyyaml
    - packaging
    - gitpython
    - jellyfish
    - tqdm
    - line_profiler
    - memory_profiler
    - colorama

test:
  imports:
    - sciris
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://sciris.org
  summary: Fast, flexible tools to simplify scientific Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Sciris is a library of tools that can help make writing scientific 
    Python code easier and more pleasant. Built on top of NumPy and 
    Matplotlib, Sciris provides functions covering a wide range of common 
    array, file I/O, and plotting operations.
  doc_url: https://docs.sciris.org/
  dev_url: https://github.com/sciris/sciris

extra:
  recipe-maintainers:
    - cliffckerr
